### PR TITLE
Small fix to avoid doubling of relative path in output filename.

### PR DESCRIPTION
**Pull request by glenn-horton-smith**
I noticed that if a relative path is used for the input file, the output directory has that relative path doubled. E.g., if the input filename is  ../test.txt, the output is written to ../../test.zip.  This small fix corrects that little problem.

### CODE REVIEW

**Comment by JeffFessler** [comment]
Your heading says "small fix" but it seems you have changed 4 files and 100s of lines!
(It looks like you made unrelated commits to the same branch after making this PR.)

**Comment by glenn-horton-smith** [comment]
Oh, oops, i though i had specified just the branch fix. Sorry about that.
Yes, the master branch in my fork has support for Canvas calculated
(formula) questions. It actually works! Using it for my next quiz. Was
going to write to you about that next.
Let's close this pull request and I'll make a proper PR with just the tiny
1-line fix for the output path. I'll open an issue about the calculated
question support feature.

**Comment by JeffFessler** [comment]
@glenn-horton-smith I'm an enthusiastic user not a maintainer BTW.
The calculated questions sounds very interesting.  When you make a PR request for that I hope  you will also include an  update to the README to show an example of how to use it.  Thanks!

**Comment by glenn-horton-smith** [comment]
Closing pull request due to my mistake with branch.

**Pull request closed without merging**
